# Generated by Django 4.1.2 on 2022-10-26 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_remove_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='price_by_Flight',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price_by_Train',
        ),
    ]
